<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;netstandard2.0;netstandard2.1</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>LiteOrm 远程服务调用</Description>
    <AssemblyVersion>8.0.3.0</AssemblyVersion>
    <FileVersion>8.0.3.0</FileVersion>
    <VersionPrefix>8.0.3</VersionPrefix>
    <PackageReleaseNotes>
      新增 Remote/Server 身份认证机制，支持 Cookie/JWT 等多种认证方式，支持UserName/Password、ClientID/Key模式，支持单用户/多用户身份模式；
      新增 RequestID 用于跟踪请求；
    </PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/danjiewu/LiteOrm</PackageProjectUrl>
    <Copyright>Copyright @ 2026 danjiewu</Copyright>
    <RepositoryUrl>https://github.com/danjiewu/LiteOrm.git</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.Remote.nuget.md</PackageReadmeFile>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.Remote.nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiteOrm.Common\LiteOrm.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Castle.Core.AsyncInterceptor" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
  </ItemGroup>

</Project>
